import type { PointCloudSceneConfig } from "./types";

export const taichuEntrySceneConfig: PointCloudSceneConfig = {
  id: "taichu-entry-void",
  asset: {
    assetUrl: "/entry-point-clouds/star-particle-world.ply",
    mobileAssetUrl: "/entry-point-clouds/star-particle-world.ply",
    renderMode: "gaussian-splat",
    position: { x: 0, y: 0, z: 0 },
    rotation: { x: 0, y: 0, z: 0 },
    scale: 1,
  },
  fallbackEnabled: true,
  cameraNav: {
    position: { x: 0, y: -42, z: 132 },
    target: { x: 2, y: -54, z: 500 },
    fov: 68,
  },
  cameraEnter: {
    position: { x: 4, y: -40, z: 164 },
    target: { x: 8, y: -54, z: 536 },
    fov: 64,
  },
  cameraChapter: {
    position: { x: 14, y: -38, z: 196 },
    target: { x: 18, y: -52, z: 580 },
    fov: 60,
  },
  cameraFocus: {
    position: { x: 22, y: -34, z: 232 },
    target: { x: 30, y: -46, z: 616 },
    fov: 56,
  },
  exploration: {
    enabled: false,
    bounds: {
      min: { x: -72, y: -120, z: 82 },
      max: { x: 72, y: 42, z: 184 },
    },
    keyboardSpeed: 62,
    wheelSpeed: 0.2,
    damping: 0.88,
  },
  material: {
    pulseStrength: 0.18,
    audioLow: 0,
    audioMid: 0,
    audioHigh: 0,
  },
  foregroundPlanet: {
    enabled: true,
    position: { x: 58, y: -38, z: 245 },
    mobilePosition: { x: 16, y: -40, z: 245 },
    radius: 18.2,
    mobileRadius: 8.6,
    opacity: 0.96,
    cloudOpacity: 0.36,
    atmosphereOpacity: 0.14,
    decorOpacity: 0,
    rotationSpeed: 0.018,
    cloudRotationSpeed: -0.012,
    tiltDegrees: -16,
    enterDrift: { x: 22, y: -3, z: -18 },
    texturePaths: {
      albedo: "/entry-planet/02-planet-albedo.png",
      bump: "/entry-planet/03-planet-bump.png",
      roughness: "/entry-planet/04-planet-roughness.png",
      cloudAlpha: "/entry-planet/05-planet-cloud-alpha.png",
      emission: "/entry-planet/06-planet-emission.png",
      atmosphereGlow: "/entry-planet/07-planet-atmosphere-glow.png",
      particleRing: "/entry-planet/08-planet-particle-ring.png",
      foregroundFog: "/entry-planet/09-homepage-foreground-fog.png",
      runeCircle: "/entry-planet/10-rune-circle-overlay.png",
    },
  },
  hotspots: [
    {
      id: "world-seed",
      label: "太初之种",
      position: { x: 0.4, y: 18, z: 150 },
      radius: 34,
      chapterId: "entry",
    },
  ],
};
