"""Product and data contract models for the single-novel workspace."""

from taichu.domain.models.ai_card import (
    AIResultCard,
    AIResultCardStatus,
    AIResultCardType,
    AIWorkflow,
)
from taichu.domain.models.chapter import (
    Chapter,
    ChapterManifest,
    ChapterStatus,
    Volume,
)
from taichu.domain.models.mvp_inbox import (
    MVPInboxEntryType,
    MVPInboxIdea,
    MVPInboxIssue,
    MVPInboxPendingFact,
    MVPInboxPriority,
    MVPInboxStatus,
)
from taichu.domain.models.mvp_source_ref import (
    SourceReference,
    SourceReferenceType,
)
from taichu.domain.models.outline import (
    OutlineChapter,
    OutlineVolume,
    WritingOutline,
)
from taichu.domain.models.preferences import (
    EditorBackground,
    EditorFontStyle,
    EditorPreferences,
)
from taichu.domain.models.inbox import (
    ChapterIssue,
    ChapterIssueSource,
    ChapterIssueStatus,
    IdeaCard,
    IdeaCardSource,
    IdeaCardStatus,
)
from taichu.domain.models.import_batch import ImportBatch
from taichu.domain.models.knowledge import (
    CharacterCard,
    KnowledgeCard,
    KnowledgeCardLifecycle,
    KnowledgeCardType,
)
from taichu.domain.models.structured_knowledge import (
    KnowledgeFieldOption,
    KnowledgeFieldMergeStrategy,
    KnowledgeFieldSchema,
    KnowledgeSchemaFieldType,
    KnowledgeTypeSchema,
    StructuredKnowledgeCard,
    StructuredKnowledgeLifecycle,
    StructuredKnowledgeSourceOrigin,
    StructuredKnowledgeType,
    all_knowledge_card_field_keys,
    all_knowledge_type_schemas,
    knowledge_type_field_keys,
    knowledge_field_merge_strategy,
    knowledge_type_label,
    knowledge_type_schema,
    type_specific_field_keys,
)
from taichu.domain.models.pending_fact import (
    PendingFact,
    PendingFactStatus,
    PendingFactType,
    ProposedBy,
)
from taichu.domain.models.source_ref import (
    SourceAnchorType,
    SourceRef,
    SourceRefSourceType,
)
from taichu.domain.models.summary import ChapterSummary, ChapterSummaryStatus
from taichu.domain.models.export import ExportBundle, ExportFile
from taichu.domain.models.writing_ai import (
    WritingAIButtonType,
    WritingAIInput,
    WritingAIOutputType,
    WritingAIPromptSnapshot,
    WritingAIReferenceScope,
    WritingAIRetrievalContext,
    WritingAIRetrievalEvidenceItem,
    WritingAIRun,
    WritingAIRunStatus,
    WritingAISelectionRange,
    WritingAIStructuredOutput,
)

__all__ = [
    "AIResultCard",
    "AIResultCardStatus",
    "AIResultCardType",
    "AIWorkflow",
    "Chapter",
    "ChapterManifest",
    "ChapterStatus",
    "Volume",
    "OutlineChapter",
    "OutlineVolume",
    "WritingOutline",
    "SourceReference",
    "SourceReferenceType",
    "MVPInboxEntryType",
    "MVPInboxIdea",
    "MVPInboxIssue",
    "MVPInboxPendingFact",
    "MVPInboxPriority",
    "MVPInboxStatus",
    "EditorBackground",
    "EditorFontStyle",
    "EditorPreferences",
    "IdeaCard",
    "IdeaCardSource",
    "IdeaCardStatus",
    "ChapterIssue",
    "ChapterIssueSource",
    "ChapterIssueStatus",
    "ImportBatch",
    "CharacterCard",
    "KnowledgeCard",
    "KnowledgeCardLifecycle",
    "KnowledgeCardType",
    "KnowledgeFieldOption",
    "KnowledgeFieldMergeStrategy",
    "KnowledgeFieldSchema",
    "KnowledgeSchemaFieldType",
    "KnowledgeTypeSchema",
    "StructuredKnowledgeCard",
    "StructuredKnowledgeLifecycle",
    "StructuredKnowledgeSourceOrigin",
    "StructuredKnowledgeType",
    "all_knowledge_card_field_keys",
    "all_knowledge_type_schemas",
    "knowledge_type_field_keys",
    "knowledge_field_merge_strategy",
    "knowledge_type_label",
    "knowledge_type_schema",
    "type_specific_field_keys",
    "PendingFact",
    "PendingFactStatus",
    "PendingFactType",
    "ProposedBy",
    "SourceAnchorType",
    "SourceRef",
    "SourceRefSourceType",
    "ChapterSummary",
    "ChapterSummaryStatus",
    "ExportBundle",
    "ExportFile",
    "WritingAIButtonType",
    "WritingAIInput",
    "WritingAIOutputType",
    "WritingAIPromptSnapshot",
    "WritingAIReferenceScope",
    "WritingAIRetrievalContext",
    "WritingAIRetrievalEvidenceItem",
    "WritingAIRun",
    "WritingAIRunStatus",
    "WritingAISelectionRange",
    "WritingAIStructuredOutput",
]
